### ISSUE TITLE
Configurable Dependency Version Resolution Strategy

### ISSUE THREAD

**Issue by gnodet** [apache/maven#11391]
## Summary
Currently, Maven's resolver treats direct dependencies (declared in a POM) as absolute version requirements that always override transitive dependencies, even when transitive deps require higher versions. This requires extensive use of `<dependencyManagement>` blocks to control resolution. This RFE proposes a configurable mechanism to allow more flexible version resolution while maintaining user control.

## Motivation
- **Current Pain Point**: Developers must explicitly manage many transitive dependencies through `<dependencyManagement>` to avoid version conflicts
- **Flexibility Need**: Different projects have different requirements—some need strict version control, others prefer automatic upgrades to satisfy transitive requirements
- **Control Concern**: Any change to default resolution behavior risks breaking builds unexpectedly (e.g., in reactor builds where in-development versions could be downgraded)

## Proposed Solution
Introduce an optional `directDependencyStrategy` attribute at both project and dependency levels to control how direct dependencies participate in version conflict resolution:

```xml
<project directDependencyStrategy="flexible">
  <dependencies>
    <!-- Strategy "flexible" applies: allows transitive deps to override this version -->
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>lib-a</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>
</project>
```

Or at the individual dependency level:
```xml
<dependency>
  <groupId>com.example</groupId>
  <artifactId>lib-b</artifactId>
  <version>2.0</version>
  <directDependencyStrategy>fixed</directDependencyStrategy>  <!-- This version always wins -->
</dependency>
```

## Strategy Options
- **`fixed` (default)**: Direct dependency version is absolute; always wins version conflicts (current behavior)
- **`flexible`**: Allow the configured version resolver to apply its normal conflict resolution rules (e.g., highest version, nearest) even for direct dependencies, permitting transitive dependencies to override this direct dependency

## Configuration
Strategy default can be controlled at multiple levels (lowest precedence to highest):

1. **Maven Configuration**: `maven.resolver.directDependencyStrategy` property
   ```xml
   <properties>
     <maven.resolver.directDependencyStrategy>flexible</maven.resolver.directDependencyStrategy>
   </properties>
   ```

2. **Project Level**: `<project directDependencyStrategy="...">` in POM

3. **Dependency Level**: `<directDependencyStrategy>` within individual `<dependency>` block

## Consumer Behavior
When a direct dependency with non-default strategy is consumed as a transitive dependency:
- The `directDependencyStrategy` attribute should be removed/not applied
- Resolution follows normal transitive dependency rules using the active conflict resolver
- Consumer POM controls conflict resolution via their own direct dependency strategies

## Safeguards
- **Build Validation**: Maven warns if unexpected downgrades occur during resolution when using `flexible` strategy
- **Reactor Awareness**: In-development versions in reactor builds always take precedence over deployed versions
- **Explicit Override**: Individual dependencies can override project-level strategy setting

## Benefits
- **Less Configuration**: Developers need fewer `<dependencyManagement>` entries
- **Explicit Intent**: Clear declaration of whether a version is fixed or flexible
- **Gradual Adoption**: Backward compatible; defaults preserve current behavior
- **Flexibility**: Works with any conflict resolver implementation (highest, nearest, etc.)
- **Platform Compatibility**: Works alongside platform/BOM-based dependency management

## Implementation Notes
- Extends `ConfigurableVersionSelector` to check strategy configuration before applying fixed direct dependency preference
- Requires POM model updates to support `directDependencyStrategy` attribute
- Consumer POM transformations should strip `directDependencyStrategy` attributes during publishing
- Strategy resolution follows hierarchy: dependency-level > project-level > Maven property > hardcoded default

**Comment by vlsi** [comment]
> Consumer POM transformations should strip `directDependencyStrategy` attributes during publishing

Ah. I missed the idea is to strip the attribute on publishing.

In that regard, it makes no sense to have `strict`/`reject`/`require` version types.

If the new attribute was kept when publishing, then transitive dependencies could bring requirements like `require 1.4 & reject [2.0,)` below.

----

>What would be the behaviour of the reject value ? Act like require, but fail if the version would change ?

My thought was as follows: sometime later the following cases might be helpful for both producers and consumers.

* `require 1.4 & reject [2.0,)`
  In other words: "I require 1.4", however, if somebody requests 2.1, then the resolution should fail as I know there are incompatibilities.
* `strict 1.7`
  In other words, "this works with 1.7 only"

In that regard, `versionType` could control the way conflicts would be resolved.
The initial implementation could be just `strict` + `require` (or `fixed` + `flexible`).

However, users would require a separate knob for "nearest vs highest" anyways, so their combinations would be as follows:

* strict + nearest: current behavior
* strict + highest: might be helpful for "forced override" of a version. I hope it should rarely be used
* require + highest: solves NoClassDefFoundError caused by nearest. I hope this would become a new default one day
* require + nearest: it is probably the same as `strict + nearest`. We could issue warning and be done with it

**Comment by vlsi** [comment]
@gnodet , I have read the proposal again, and I do not see user story in it.
In other words, I do not see what would really change for the end-user if they flip the added `directDependencyStrategy` setting. It would be great if you could clarify the end-to-end flow

**Comment by gnodet** [comment]
> [@gnodet](https://github.com/gnodet) , I have read the proposal again, and I do not see user story in it. In other words, I do not see what would really change for the end-user if they flip the added `directDependencyStrategy` setting. It would be great if you could clarify the end-to-end flow

Given this is a breaking change, the idea is to let the user opt-in by changing using the maven configuration property in `.mvn/maven.properties` or by setting the `directDependencyStrategy="flexible"` globally on the `project` element.  The flag could also be changed in `~/.mvn/maven.properties` or `$MAVEN_HOME/conf/maven.properties` to have a global effect for all projects.
A possible (but optional) enhancement would be to make the flag available for each dependency as stated in the original proposal, but this would require much more change (first in the POM object model, then in the resolver), while the global flag should be implementable only in Maven.

Once the user switches to `flexible`, the direct dependencies would be subject to conflict resolution.  They are currently excluded, per the rule that, if the user explicitly specifies a version for a given dependency, that one should be honored.  So basically direct dependencies always win during conflict resolution.

So in your original `mvn-mediation` use case, we have `lib-a` depending on `guice:5.0.1`, `lib-b` depending on `guice:3.0`, `example-application` depending on `lib-a`, `lib-b` and `guice:3.0`.  With the current behaviour, `example-application` has a direct dependency on `guice:3.0`, so that version wins.  If the user switches the project to use `flexible`, the direct dependency suddenly becomes subject to dependency resolution.  Changing `directDependencyStrategy ` only would not really change the output of the resolution, since the default version conflict resolution favours the dependencies closer to the top of the tree.  However, if the user also changes the conflict resolution to use `highest`, then, the direct dependency would be subject to higher policy conflict resolution and would be switched to `guice:5.0.1`.

So this has to be coupled with selecting the highest version, else, there's not much point.

Given the flag only affects direct dependencies, this means that when a library is consumed by another project, the dependencies of the libraries become transitive dependencies, and the flag no longer apply.  It thus becomes completely useless, which is a good thing, as it allows Maven to remove it from the consumer POM, since consumer POMs have a 4.0.0 model, and the flag could not be included anyway.

As a first step, I would not include the per-dependency flag, I'm not really it's worth it at the moment.  If we don't want to change the model, we could also only use the maven property, just like we have with the `highest` property for the dependency conflict resolver...

**Comment by rmannibucau** [comment]
`flexible-highest` for a common use case which is a downgrade? `bom-transitive` maybe or `unknown` to be clear it will look random for end users maybe

**Comment by vlsi** [comment]
> Given this is a breaking change, the idea is to let the user opt-in by changing using the maven configuration property in .mvn/maven.properties or by setting the directDependencyStrategy="flexible" globally on the project element

@gnodet , do you mean activation of the property would automatically switch the resolution from "nearest to highest"?
Otherwise I do not see how `directDependencyStrategy=flexible` changes anything.

**Comment by vlsi** [comment]
If you think of a global property that changes the resolution strategy, then what do you think of the following?

1. Global property in `maven.properties` to configure resolution mode (e.g. `maven.dependency.resolution.mode`): `nearest` (default to keep the current behavior), `highest`
2. Dependency-level property like `versionType` = `strict` (default for `nearest`), `require` (default for `highest`)

In that case, there's no need in project-level `dependencyVersionType`.

**Comment by desruisseaux** [comment]
I would like to mention another scenario to keep in mind. I have not yet explored how the `jar --hash-module` option work. But from [this example](https://stackoverflow.com/questions/45387075/how-to-use-hash-modules-and-module-path-options-of-jdk-9-jar-tool) we can get (output of `jar --describe-module`):

```
exports com.me.util
requires java.base mandated
hashes com.me SHA-256 85c0539e4ca9a01b00f4c29a1a8b01cd452d1d97f437166b8bb415046dac65cb
```

Therefore, we may need to implement in the future a strategy that requires the SHA-256 hash of modular JAR files to match. I do not yet understand well in which direction those hashes work, I just wanted to mention that we may have a use case for this kind of scenario.

**Comment by rmannibucau** [comment]
Guys, can we step back please? I totally understand this is trivial to add a new strategy which can do whatever we do want but how do you converge in the consumer pom since we do not flatten without transitive deps (explicit dep list)?
Is it ok to expose a tree which is not the one you did use to build and validate your project (not IMHO)?

**Comment by vlsi** [comment]
>We could create a strategy which, instead of saying "choose higher version", said "choose the version with matching SHA 256". I do not said that we need to do that, just mentioning as a possibility.

I am afraid the selection based on hash is impractical for Java ecosystem at the moment:
* Imagine there's https://repo1.maven.org/maven2/commons-io/commons-io/
  How would you find which one corresponds to hash `12ccc61c573aed8a193f9727dc33795eba29d7c5`?
  Maven repository layout is not designed to fetch artifacts by their hash.
* How would you perform conflict resolution if different libraries require different hash values for `commons-io`?

**Comment by desruisseaux** [comment]
> How would you find which one corresponds to hash 12ccc61c573aed8a193f9727dc33795eba29d7c5?

If the dependency tree contains two versions of `commons-io` (for example), the hash is computed for those two versions from the JAR files cached in the local `.m2` repository.

> Maven repository layout is not designed to fetch artifacts by their hash.

I know, but we don't need to search by hash. We only need to compute the hash of files in conflict after they have been downloaded.

> How would you perform conflict resolution if different libraries require different hash values for commons-io?

The hash prevails if this is what the user requested. It would not be the default, only a strategy that users can select if this what they want.

**Comment by rmannibucau** [comment]
@cstamas doesn't the jpms module hash thing overlaps with what you did about CI build harnessing so could converge?

**Comment by rmannibucau** [comment]
> so this can only affect build time behavior.

it is my concern, your project view is different than your consumer view, not sure it is that sane since you can ask all your consumer to do work to be aligned with your expectations
