### PR TITLE
[3.9.x] [MNG-8136] Update Eclipse Sisu to 0.9.0.M3

### PR DESCRIPTION
**Pull request by cstamas**
Update Eclipse Sisu 0.9.0.M3 (carries ASM 9.7).

---

https://issues.apache.org/jira/browse/MNG-8136

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by olamy — APPROVED** [review]

**Comment by chrjohn** [comment]
Sorry, not exactly sure what causes this, but after upgrade of maven-plugin-api from 3.9.7 to 3.9.8 my builds start failing with:
```
java.lang.NoSuchMethodError: org.eclipse.sisu.space.SpaceModule.<init>(Lorg/eclipse/sisu/space/ClassSpace;Lorg/eclipse/sisu/space/BeanScanning;Z)V
	at org.eclipse.sisu.plexus.PlexusAnnotatedBeanModule.<init>(PlexusAnnotatedBeanModule.java:93)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:204)
	at org.apache.maven.plugin.testing.AbstractMojoTestCase.setupContainer(AbstractMojoTestCase.java:264)
	at org.apache.maven.plugin.testing.AbstractMojoTestCase.getContainer(AbstractMojoTestCase.java:298)
	at org.apache.maven.plugin.testing.AbstractMojoTestCase.setUp(AbstractMojoTestCase.java:152)
	at org.apache.maven.plugin.testing.MojoRule$2.evaluate(MojoRule.java:304)
```

**Comment by kwin** [comment]
@chrjohn Seems that your classpath contains different versions of `sisu.inject` and `sisu.plexus`. Make sure both have the same version.

**Comment by chrjohn** [comment]
> @chrjohn Seems that your classpath contains different versions of `sisu.inject` and `sisu.plexus`. Make sure both have the same version.

Thanks for the pointer @kwin , I think this could only be via some other plugins that I use. But will check. Thanks again.

**Comment by cstamas** [comment]
See https://github.com/quickfix-j/quickfixj/pull/826#issuecomment-2175711410
