### ISSUE TITLE
NoSuchMethodError: 'void org.apache.maven.toolchain.DefaultToolchain.<init>

### ISSUE THREAD

**Issue by hboutemy** [apache/maven#11973]
### Affected version

4.0.0-RC-5
see https://github.com/apache/maven-toolchains-plugin/pull/152

### Bug description

maven-toolchain-plugin IT failure:
```
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 6, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  use-custom-toolchain/pom.xml
[INFO] -------------------------------------------------
```

```
Caused by: java.lang.NoSuchMethodError: 'void org.apache.maven.toolchain.DefaultToolchain.<init>(org.apache.maven.toolchain.model.ToolchainModel, java.lang.String, org.codehaus.plexus.logging.Logger)'
    at org.apache.maven.plugins.toolchains.its.custom.CustomToolchainImpl.<init>(CustomToolchainImpl.java:37)
    at org.apache.maven.plugins.toolchains.its.custom.CustomToolchainFactory.createToolchain(CustomToolchainFactory.java:61)
    at org.apache.maven.toolchain.ToolchainManagerFactory$2.createToolchain(ToolchainManagerFactory.java:142)
    at org.apache.maven.impl.DefaultToolchainManager.createToolchain(DefaultToolchainManager.java:106)
```

caused by #562

**Comment by Pratapchandradeo** [comment]
Hi @hboutemy,

Can I start working on this issue? It would be great if you could assign it to me.

Thanks!
