### ISSUE TITLE
[MNG-2917] Ant classpath issue in maven 2.0.6

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4573]
**[Yuri Schimke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yuri)** opened **[MNG-2917](https://issues.apache.org/jira/browse/MNG-2917?redirect=false)** and commented

This was working in 2.0.5.  Unfortunately I'm guessing its related to the woefully bad xdoclet-maven-plugin

The main error is that the xdoclet-maven-plugin can't find one of the ant classes

Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/PropertyHelper

---

this realm = app0.child-container[org.codehaus.mojo:xdoclet-maven-plugin]
urls[0] = file:/C:/Docume~1/nbk7xsp/.m2/repository/org/codehaus/mojo/xdoclet-maven-plugin/1.0-alpha-2/xdoclet-maven-plugin-1.0-alpha-2.jar
urls[1] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-wsee-module/1.2.3/xdoclet-wsee-module-1.2.3.jar
urls[2] = file:/C:/Docume~1/nbk7xsp/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
urls[3] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-jboss-module/1.2.3/xdoclet-jboss-module-1.2.3.jar
urls[4] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-xdoclet-module/1.2.3/xdoclet-xdoclet-module-1.2.3.jar
urls[5] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-orion-module/1.2.3/xdoclet-orion-module-1.2.3.jar
urls[6] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-jmx-module/1.2.3/xdoclet-jmx-module-1.2.3.jar
urls[7] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-ibm-module/1.2.3/xdoclet-ibm-module-1.2.3.jar
urls[8] = file:/C:/Docume~1/nbk7xsp/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar
urls[9] = file:/C:/Docume~1/nbk7xsp/.m2/repository/commons-collections/commons-collections/2.1/commons-collections-2.1.jar
urls[10] = file:/C:/Docume~1/nbk7xsp/.m2/repository/ant/ant/1.5.2/ant-1.5.2.jar
urls[11] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-apache-module/1.2.3/xdoclet-apache-module-1.2.3.jar
urls[12] = file:/C:/Docume~1/nbk7xsp/.m2/repository/ant/ant-launcher/1.6.5/ant-l
auncher-1.6.5.jar
urls[13] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-fr_FR-locale/1.2.3/xdoclet-fr_FR-locale-1.2.3.jar
urls[14] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-objectweb-module/1.2.3/xdoclet-objectweb-module-1.2.3.jar
urls[15] = file:/C:/Docume~1/nbk7xsp/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.0/maven-antrun-plugin-1.0.jar
urls[16] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-java-module/1.2.3/xdoclet-java-module-1.2.3.jar
urls[17] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-exolab-module/1.2.3/xdoclet-exolab-module-1.2.3.jar
urls[18] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-bea-module/1.2.3/xdoclet-bea-module-1.2.3.jar
urls[19] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-mvcsoft-module/1.2.3/xdoclet-mvcsoft-module-1.2.3.jar
urls[20] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-sun-module/1.2.3/xdoclet-sun-module-1.2.3.jar
urls[21] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-spring-module/1.2.3/xdoclet-spring-module-1.2.3.jar
urls[22] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-de-locale/1.2.3/xdoclet-de-locale-1.2.3.jar
urls[23] = file:/C:/Docume~1/nbk7xsp/.m2/repository/jboss/jboss-j2ee/3.2.1/jboss-j2ee-3.2.1.jar
urls[24] = file:/C:/Docume~1/nbk7xsp/.m2/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar
urls[25] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-web-module/1.2.3/xdoclet-web-module-1.2.3.jar
urls[26] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-caucho-module/1.2.3/xdoclet-caucho-module-1.2.3.jar
urls[27] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-jdo-module/1.2.3/xdoclet-jdo-module-1.2.3.jar
urls[28] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-tjdo-module/1.2.3/xdoclet-tjdo-module-1.2.3.jar
urls[29] = file:/C:/Docume~1/nbk7xsp/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
urls[30] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-openejb-module/1.2.3/xdoclet-openejb-module-1.2.3.jar
urls[31] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-oracle-module/1.2.3/xdoclet-oracle-module-1.2.3.jar
urls[32] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-hp-module/1.2.3/xdoclet-hp-module-1.2.3.jar
urls[33] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-webwork-module/1.2.3/xdoclet-webwork-module-1.2.3.jar
urls[34] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-mx4j-module/1.2.3/xdoclet-mx4j-module-1.2.3.jar
urls[35] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-solarmetric-module/1.2.3/xdoclet-solarmetric-module-1.2.3.jar
urls[36] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet/1.2.3/xdoclet-1.2.3.jar
urls[37] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-jsf-module/1.2.3/xdoclet-jsf-module-1.2.3.jar
urls[38] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-pt_BR-locale/1.2.3/xdoclet-pt_BR-locale-1.2.3.jar
urls[39] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-pramati-module/1.2.3/xdoclet-pramati-module-1.2.3.jar
urls[40] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-borland-module/1.2.3/xdoclet-borland-module-1.2.3.jar
urls[41] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-ejb-module/1.2.3/xdoclet-ejb-module-1.2.3.jar
urls[42] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-hibernate-module/1.2.3/xdoclet-hibernate-module-1.2.3.jar
urls[43] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-sybase-module/1.2.3/xdoclet-sybase-module-1.2.3.jar
urls[44] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-libelis-module/1.2.3/xdoclet-libelis-module-1.2.3.jar
urls[45] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-mockobjects-module/1.2.3/xdoclet-mockobjects-module-1.2.3.jar
urls[46] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-portlet-module/1.2.3/xdoclet-portlet-module-1.2.3.jar
urls[47] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xjavadoc/1.1/xjavadoc-1.1.jar
urls[48] = file:/C:/Docume~1/nbk7xsp/.m2/repository/xdoclet/xdoclet-macromedia-module/1.2.3/xdoclet-macromedia-module-1.2.3.jar
Number of imports: 4
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185
this realm = plexus.core
urls[0] = file:/c:/java/maven-2.0.6/lib/maven-core-2.0.6-uber.jar
Number of imports: 4
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185

---

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet': Unable to find the mojo 'org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet' in the plugin 'org.codehaus.mojo:xdoclet-maven-plugin'
org/apache/tools/ant/PropertyHelper
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet': Unable to find the mojo 'org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet' in the plugin 'org.codehaus.mojo:xdoclet-maven-plugin'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:543)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet' in the plugin 'org.codehaus.mojo:xdoclet-maven-plugin'
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:571)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:421)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
... 16 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojoorg.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet', it could not be created
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:335)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:562)
... 18 more
Caused by: org.codehaus.plexus.component.factory.ComponentInstantiationException: Could not instanciate component: role: 'null', implementation: 'org.codehaus.mojo.xdoclet.XDocletMojo'
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.makeException(JavaComponentFactory.java:77)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:62)
at org.codehaus.plexus.DefaultPlexusContainer.createComponentInstance(DefaultPlexusContainer.java:1464)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:93)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
... 20 more
Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/PropertyHelper
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2357)
at java.lang.Class.getConstructor0(Class.java:2671)
at java.lang.Class.newInstance0(Class.java:321)
at java.lang.Class.newInstance(Class.java:303)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:44)
... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4 seconds
[INFO] Finished at: Mon Apr 02 11:46:23 BST 2007
[INFO] Final Memory: 5M/10M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.6

**Comment by jira-importer** [comment]
**[Yuri Schimke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yuri)** commented

I'm closing this one because after making some cleanups of our POMs etc, the issue has gone away.

I think the maven 2.0.6 was just triggering some latent issue.

**Comment by jira-importer** [comment]
**[Yuri Schimke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yuri)** commented

This seems like the most appropriate solution

http://www.nabble.com/Re%3A-maven-2.0.6-and-xdoclet-maven-plugin-p9839377s177.html

\<plugin>
\<artifactId>xdoclet-maven-plugin\</artifactId>
\<groupId>org.codehaus.mojo\</groupId>
\<executions>
\<execution>
\<id>xdoclet\</id>
\<phase>generate-resources\</phase>
\<goals>
\<goal>xdoclet\</goal>
\</goals>
\</execution>
\</executions>
\<configuration>
\<tasks>
\<hibernatedoclet
destdir="${project.build.outputDirectory}"
mergeDir="${basedir}/src/main/merge">
\<fileset dir="${basedir}/src/main/java"
includes="**/domain/*.java" />
\<hibernate version="3.0" />
\</hibernatedoclet>
\</tasks>
\</configuration>
\<dependencies>
\<dependency>
\<groupId>ant\</groupId>
\<artifactId>ant\</artifactId>
\<version>1.6.5\</version>
\</dependency>
\</dependencies>
\</plugin>

**Comment by jira-importer** [comment]
**[Petr Kozelka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pkozelka)** commented

I just want to confirm that this really helped to me too.
In particular, adding the explicit ant-1.6.5 dependency made the difference.
There must be some magic, because the maven-antrun-plugin, used by xdoclet-maven-plugin, itself depends on ant-1.6.5, but I didn't bother to explore it deeper.
