### PR TITLE
Fix #11973: Restore backward-compatible DefaultToolchain constructor

### LINKED ISSUE #11973: NoSuchMethodError: 'void org.apache.maven.toolchain.DefaultToolchain.<init>
### Affected version

4.0.0-RC-5
see https://github.com/apache/maven-toolchains-plugin/pull/152

### Bug description

maven-toolchain-plugin IT failure:
```
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 6, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  use-custom-toolchain/pom.xml
[INFO] -------------------------------------------------
```

```
Caused by: java.lang.NoSuchMethodError: 'void org.apache.maven.toolchain.DefaultToolchain.<init>(org.apache.maven.toolchain.model.ToolchainModel, java.lang.String, org.codehaus.plexus.logging.Logger)'
    at org.apache.maven.plugins.toolchains.its.custom.CustomToolchainImpl.<init>(CustomToolchainImpl.java:37)
    at org.apache.maven.plugins.toolchains.its.custom.CustomToolchainFactory.createToolchain(CustomToolchainFactory.java:61)
    at org.apache.maven.toolchain.ToolchainManagerFactory$2.createToolchain(ToolchainManagerFactory.java:142)
    at org.apache.maven.impl.DefaultToolchainManager.createToolchain(DefaultToolchainManager.java:106)
```

caused by #562

### PR DESCRIPTION
**Pull request by gnodet**
## Summary

Fixes #11973

Custom toolchain implementations compiled against Maven 3.x call `DefaultToolchain(ToolchainModel, String, org.codehaus.plexus.logging.Logger)`, which was removed when Maven 4 switched to SLF4J. This causes `NoSuchMethodError` at runtime.

This PR adds two deprecated backward-compatible constructors that accept the old Plexus `Logger` parameter and delegate to the existing SLF4J-based constructors.

See also: https://github.com/apache/maven-toolchains-plugin/pull/152

## Test plan

- [x] `mvn install -DskipTests` builds successfully
- [x] Run maven-toolchains-plugin ITs with custom toolchain (`use-custom-toolchain`)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by hboutemy — APPROVED** [review]
tested with maven-toolchain-plugin: it fixes the issue
very good, small fix
thanks

**Review by slachiewicz — APPROVED** [review]
