### ISSUE TITLE
[MNG-6221] Maven cannot build with Java 1.8.0_131

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7646]
**[Erich Steiger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=esteiger)** opened **[MNG-6221](https://issues.apache.org/jira/browse/MNG-6221?redirect=false)** and commented

After upgrading from Oracle Java 1.8.0_102 to Oracle Java 1.8.0_131, it is not possible to build anymore with maven. Tested with maven 3.3.9 and 3.5.0.

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.example 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] Error injecting: org.apache.maven.wagon.providers.http.HttpWagon
java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at java.security.Provider$Service.getImplClass(Provider.java:1634)
at java.security.Provider$Service.newInstance(Provider.java:1592)
at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
...

---

**Affects:** 3.3.9, 3.5.0

**Comment by jira-importer** [comment]
**[Stephen Connolly](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stephenc)** commented

Could you provide a minimum sample pom that reproduces the issue? (I am able to build with Java 1.8.0_131 and Maven 3.5.0 so I wonder if this is an issue with custom extensions)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Looking forward to an example, I'd take a look.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Two months w/o a sample project.
